GET http://localhost:3001/api/notes HTTP/1.1

###
POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json

{
  "content": "This is a new note",
  "important": true
}

###
GET http://localhost:3001/api/notes/62c6dfa72c2f8a7d1bfd89 HTTP/1.1

###
DELETE http://localhost:3001/api/notes/62c6e169bc5bf5a74b7c08a0 HTTP/1.1
